models:
  - name: dim_listings_cleansed
    description: "This table contains the cleansed listings data for Airbnb."
    data_tests:
      - min_row_count:
          arguments:
            min_row: 1000
          config:
            severity: error
    columns:
      - name: listing_id
        description: "The unique identifier for each listing."
        data_tests:
          - unique
          - not_null

      - name: host_id
        description: "The unique identifier for each host."
        data_tests:
          - not_null
          - relationships:
              arguments:
                to: ref('dim_hosts_cleansed')
                field: host_id

      - name: room_type
        description: "The type of room being offered (e.g., Entire home/apt, Private room, Shared room, Hotel room)."
        data_tests:
          - accepted_values:
              arguments:
                values: ['Entire home/apt', 'Private room', 'Shared room', 'Hotel room']

      - name: minimum_nights
        description: "{{ doc('dim_listing_cleansed__minimum_nights') }}"
        data_tests:
          - positive_values

  - name: dim_hosts_cleansed
    config:
      contract:
        enforced: true
    columns:
      - name: host_id
        description: "The unique identifier for each host."
        data_type: integer
        data_tests:
          - unique
          - not_null

      - name: host_name
        description: "The name of the host."
        data_type: string
        data_tests:
          - not_null

      - name: is_superhost
        description: "Indicates whether the host is a superhost (true/false)."
        data_tests:
          - accepted_values:
              arguments:
                values: ['t', 'f']
        data_type: string

      - name: updated_at
        description: "The timestamp when the host information was last updated."
        data_type: timestamp

      - name: created_at
        description: "The timestamp when the host information was created."
        data_type: timestamp

  - name: dim_listings_w_hosts
    data_tests:
      - dbt_expectations.expect_table_row_count_to_equal_other_table:
          compare_model: source('airbnb', 'listings')
    columns:
      - name: price
        data_tests:
          - dbt_expectations.expect_column_quantile_values_to_be_between:
              quantile: .99
              min_value: 50
              max_value: 500
          - dbt_expectations.expect_column_max_to_be_between:
              max_value: 5000
              config:
                severity: warn
          - dbt_expectations.expect_column_values_to_be_of_type:
              column_type: number



 